### PR TITLE
Append disposables operator

### LINKED ISSUE #2001: Pipe operator for composite disposables
This may be crazy talk but I've toyed with `|>`ing disposables from `start` or `observe` into a `CompositeDisposable` and have been liking it. Especially for multiline signal chains where wrapping with `addDisposable` or storing the return value feels like it adds "noise".

```swift
// piped
producer
    |> map { ... }
    |> filter { ... }
    |> start { ... }
    |> disposable

// wrapped
disposable.addDisposable(producer
    |> map { ... }
    |> filter { ... }
    |> start { ... })

// stored
let producerDisposable = producer
    |> map { ... }
    |> filter { ... }
    |> start { ... }
disposable.addDisposable(producerDisposable)
```

Thoughts?

### PR DESCRIPTION
**Pull request by neilpa**
Resolves #2001

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Awesome! :sparkles:

Is this operator allowed to return a value? If so, could it return the `DisposableHandle`?

**Comment by neilpa** [comment]
I'll try, but I'm pretty sure assignment operators are statements and not expressions.

**Comment by neilpa** [comment]
It actually works, I was not expecting that.

**Comment by jspahrsummers** [comment]
:tada:

**Pull request merged**
