### PR TITLE
add DependentType

### LINKED ISSUE #1828: The correct way to bind DynamicProperty to a signal
I can bind `MutableProprty` to a signal using `<~` operator. However there is no way to do the same for `DynamicProperty`, even if nothing (technically) prevents from it, since `DynamicProperty` can also be modified. 

Do I miss something?

### PR DESCRIPTION
**Pull request by 335g**
Resolves #1828 

But I'm worried about 2 points.

1) This code allows only ```Signal<AnyObject?, _>```
2) Sense for name ```DependentType```

What do you think?

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Thanks for the pull request! :sparkles:

Can we call the protocol `MutablePropertyType`?

> This code allows only ```Signal<AnyObject?, _>```

That's fine—callers can `map` their signal values before they bind.

**Comment by 335g** [comment]
OK.

Fixed. :+1:

**Comment by jspahrsummers** [comment]
Thanks for fixing that up!

I also made a couple of tweaks to some additional stuff I noticed in 05c9f0ee811795a03c19de4e016648faf3898f96 and c4a22f2b7ab5918e298e9854d85316186f98f853. Sorry for not noticing those before.

**Comment by 335g** [comment]
I committed without worry too much. :sweat: 
Thanks for your modification.

**Pull request merged**
