### PR TITLE
Implemented retry for SignalProducer

### PR DESCRIPTION
**Pull request by NachoSoto**
Finishes #1751.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
I'll let this sit for now, as some of the notes for #1760 apply here too.

**Comment by NachoSoto** [comment]
Thanks! Working on ~~`repeat`~~ `times` now, I'll rebase this when done.

**Comment by NachoSoto** [comment]
Rebased and ready!

**Comment by jspahrsummers** [comment]
This needs the same improvements made to `times`. :pray:

**Comment by NachoSoto** [comment]
Rebasing now! :)

**Comment by jspahrsummers** [comment]
I mean that corresponding changes should be made to `retry` too. :wink:

Also, please don't rebase! Merge instead.

**Comment by NachoSoto** [comment]
I'll merge from now on, but I have to rebase in this case because this has commits that I removed in the other branch.

Is the implementation itself not correct in this case?

**Comment by jspahrsummers** [comment]
This can suffer the same O(n) growth that we discussed for `times` in #1760. It should use a counter instead.

**Comment by NachoSoto** [comment]
```swift
fit("does not overflow") {
	let original: SignalProducer<Int, TestError> = SignalProducer.try {
		return failure(.Default)
	}

	let producer = original |> retry(Int.max)
	let result = producer |> single

	expect(result?.error).to(equal(TestError.Default))
}
```

I see now :) because catch calls the closure synchronously.
Aren't you worried about not trying to reuse existing operators instead of implementing them all from scratch?

I'll fix this tonight, in any case!

**Comment by jspahrsummers** [comment]
> Aren't you worried about not trying to reuse existing operators instead of implementing them all from scratch?

If you can find a way to reuse `catch` without creating O(n) allocations, I would love to reuse it. :wink:

**Comment by NachoSoto** [comment]
Looking at `catch` implementation now I realize it's not as trivial as I was thinking :P

**Comment by neilpa** [comment]
Instead, you may be able to abstract away the recursive bits from `times` to create a more general way for restarting producers of producers. A factory of sorts for the `startWithHandler` closure.

**Comment by NachoSoto** [comment]
@neilpa you gave me a good idea to reuse the implementation between `retry` and `times`, since they're essentially the same except error VS completed.

I tried implementing it again to check if the test passed, but unfortunately an implementation like this (with the test I wrote above) still overflows the stack if everything is synchronous:
```swift
/// Ignores errors up to `count` times.
public func retry<T, E>(count: Int)(producer: SignalProducer<T, E>) -> SignalProducer<T, E> {
	precondition(count >= 0)

	if count == 0 {
		return producer
	} else {
		return SignalProducer { observer, disposable in
			let serialDisposable = SerialDisposable()
			disposable.addDisposable(serialDisposable)

			var remainingTimes = count

			let iterate = fix { recur in
				{
					producer.startWithSignal { signal, signalDisposable in
						serialDisposable.innerDisposable = signalDisposable

						signal.observe(next: { value in
							sendNext(observer, value)
						}, error: { error in
							if remainingTimes-- > 0 {
								recur()
							} else {
								sendError(observer, error)
							}
						}, completed: {
							sendCompleted(observer)
						})
					}
				}
			}

			iterate()
		}
	}
}
```

I can't think of an alternative implementation right now :/

**Comment by neilpa** [comment]
This is unavoidable without an async hop via a scheduler to force the stack to unwind. RAC 2 had [`-scheduleRecursiveBlock:`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/DesignGuidelines.md#avoid-stack-overflow-from-deep-recursion) for this problem and maybe that's the answer here. However, that precludes synchronous event delivery. It's always possible to turn a `Signal` async with `observeOn` but you cant go the other way once you've lost it.

**Comment by jspahrsummers** [comment]
I think it's fine if an infinite, synchronous signal would overflow the stack. The difference from RAC 2 is that we have the capability to interrupt a synchronous signal.

My main concern is preventing O(n) _allocations_.

**Comment by NachoSoto** [comment]
In that case, the current implementation meets that criterion :) Memory remains constant in each iteration.

**Comment by jspahrsummers** [comment]
Hm, okay.

**Pull request merged**
