### PR TITLE
DynamicProperty: don't expose signal setter

### PR DESCRIPTION
**Pull request by NachoSoto**

### CODE REVIEW

**Comment by andersio** [comment]
The `lazy` could be stripped anyway. We won't leak by creating signals through it anymore.

**Comment by NachoSoto** [comment]
@andersio it has to be `lazy` because its initialization relies on `self`. I did remove the `unowned` though which is useless.

**Comment by andersio** [comment]
@NachoSoto What I mean is it can be simply a `producer.startAndRetrieveSignal()` now.

**Comment by NachoSoto** [comment]
> @NachoSoto It can be simply a producer.startAndRetrieveSignal() now.

That's in `ReactiveSwift` and it's not exposed **[for very important reasons](https://github.com/ReactiveCocoa/ReactiveSwift/blob/67bfbd4c186f54477ea8dc228c5f5c7993ac7e9d/Sources/SignalProducer.swift#L336-L340)**.

**Pull request merged**
