### PR TITLE
[MutexType] Just extend NSRecursiveLock and remove RecursiveLock class

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by NachoSoto** [comment]
Ooooh of course, great idea 👍

**Comment by filblue** [comment]
Is `NSRecursiveLock` going to exist on Linux? 

`RecursiveLock` frees `Property.swift` from being dependent on OS X-specific mutex implementation. When we start porting `ReactiveSwift` to other platforms, we'd better reap the fruits of this abstraction layer instead of polluting both `MutableProperty.swift` and `Atomic.swift` with platform checks.

**Comment by ikesyo** [comment]
That exists in swift-corelibs-foundation: https://github.com/apple/swift-corelibs-foundation/blob/swift-3.0-PREVIEW-2/Foundation/NSLock.swift#L138

so this should not be an issue.

**Comment by andersio** [comment]
If we do not care about the cost of dispatching, why don't we use `Locking` directly?

**Pull request merged**
