### PR TITLE
Remove SWIFT_WHOLE_MODULE_OPTIMIZATION build setting

### PR DESCRIPTION
**Pull request by ikesyo**
That was for Swift 1.2.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Can you verify that this is still set as part of `-O` from the `xcconfig`?

**Comment by ikesyo** [comment]
Do you mean that we should still disable WMO (set `-O`, not `-Owholemodule` to `SWIFT_OPTIMIZATION_LEVEL `)?

**Comment by NachoSoto** [comment]
No no, just making sure that `-O` still contains `-Owholemodule` :)

**Comment by ikesyo** [comment]
Oh, thank you. `SWIFT_OPTIMIZATION_LEVEL` is `-Owholemodule`, which is from `*.xcconfig`s:

**Comment by NachoSoto** [comment]
Yup, perfect!

**Pull request merged**
