### PR TITLE
Update `SignalProducerSpec` to the new `Observer` API

### PR DESCRIPTION
**Pull request by dapenggao**

### CODE REVIEW

**Comment by NachoSoto** [comment]
Thanks!

**Comment by paulyoung** [comment]
Shouldn't those be `observer` instead of `sink`?

**Comment by dapenggao** [comment]
@paulyoung Oh! I forgot to change the name...

**Comment by paulyoung** [comment]
@dapenggao it's all good. Would definitely reinforce the new changes though.

**Pull request merged**
