### PR TITLE
[WIP] Add official podspec

### PR DESCRIPTION
**Pull request by ikesyo**
See also https://github.com/ReactiveCocoa/ReactiveSwift/pull/14.

### CODE REVIEW

**Comment by sunnycn2013** [comment]
Execuse me,, which a RAC for objective-C is the latest version?

**Comment by mdiep** [comment]
@sunnycn2013 https://github.com/ReactiveCocoa/ReactiveObjC

**Comment by andersio** [comment]
Please note that merging #3210 might block this without #3252.

**Comment by andersio** [comment]
@ikesyo Would you mind to merge #3252 into this branch?

**Comment by andersio** [comment]
@ikesyo I have merged this branch into #3252, so that we can have an integrated test. Thanks! 😸

**Pull request closed without merging**
