### PR TITLE
The Great Swiftening (a.k.a. the new 3.0)

### LINKED ISSUE #1365: ReactiveSwift
iOS and Mac OSX developers would love to continue using RAC with the recently announced language.

YAY TYPED SIGNALS!!!

### PR DESCRIPTION
**Pull request by jspahrsummers**
Resolves #1365 and #1366. Per my comments in #1369, this is intended to be a long-running branch that will eventually become RAC 3.0, supplanting the [current `3.0-development` work](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/966).

To get us started, I basically just subtree merged [jspahrsummers/RxSwift](https://github.com/jspahrsummers/RxSwift) into here, then bridged several RAC classes back and forth.

### CODE REVIEW

**Comment by tonyxiao** [comment]
What's the current status of this branch? There seems to be a lot of progress going on here but I can't find any blog posts or wiki explaining what's going on and timeline for ReactiveCocoa 3.0. Pointers appreciated!

**Comment by kastiglione** [comment]
@tonyxiao Still **W**ork **I**n **P**rogress.

Recently @jspahrsummers has answered a couple of related questions on Quora, see
http://qr.ae/BpAUK and http://qr.ae/BpAO4.

Basically, there's not much to write about until the concepts and API have stabilized enough.

**Comment by nickmshelley** [comment]
I'd really like to use this in a production app. The last update from @kastiglione suggested it's not ready yet, but that was a couple months and a few hundred commits ago. Is it still too soon?

**Comment by jspahrsummers** [comment]
@nickmshelley Please take a look at and follow https://github.com/ReactiveCocoa/ReactiveCocoa/releases. That will be the canonical source of information about production-readiness.

**Comment by nickmshelley** [comment]
@jspahrsummers Thanks, I'll follow that.

If anyone wants to volunteer any less official opinions on how much pain I will incur if I switch now, I'd appreciate it. I understand that official release pages by nature need to be pretty conservative so people don't switch early and whine.

**Comment by kastiglione** [comment]
swift-clapping

**Comment by jspahrsummers** [comment]
I [mentioned it](https://twitter.com/jspahrsummers/status/622632315500388352) on Twitter, but just to reiterate it here:

@ReactiveCocoa/reactivecocoa Thank you all (and all of our other contributors outside of the org) for everything you’ve done to help RAC 3 along! It definitely wouldn’t have been possible without you. :heart:

**Comment by paulcbetts** [comment]
:clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap:

**Comment by rpowelll** [comment]
:clap: :fireworks: :tada:

**Comment by robb** [comment]
:sparkling_heart:

**Comment by wajatimur** [comment]
Yeay, Thanks Buds.. I've waiting for this very long..

**Comment by haaakon** [comment]
:+1:

**Comment by damianesteban** [comment]
This is very exciting stuff :)  Should installing RAC with Carthage download v3.0?  It is currently download v2.5.

**Pull request merged**
