### PR TITLE
Remove the last wrapper to runtime functions

### PR DESCRIPTION
**Pull request by dmcrodrigues**
### Motivation
`objc_allocateClassPair` can now be called from ARC code.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Nice :) :shipit:

**Comment by NachoSoto** [comment]
I'll merge as soon as tests pass...

**Comment by dmcrodrigues** [comment]
Cool ✨

**Comment by ikesyo** [comment]
Thanks @dmcrodrigues and @NachoSoto! 🚢

**Pull request merged**
