### PR TITLE
[WIP] Swift documentation updates

### PR DESCRIPTION
**Pull request by neilpa**
Starts to tackle some of the other documentation updates. Moves all of the obj-c docs to `Documentation/Legacy` (_I think_ I found all the links to update).

Except for the framework overview (#2016), I've only stubbed out the new Swift pages. I'll probably be updating these sporadically so others should feel free to push to this branch too.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Awesome!

If it's okay with you, could we merge this and then continue the work in separate PRs? That way we won't have the rename cluttering up this diff, and it'll be easier to parallelize the other changes.

**Comment by neilpa** [comment]
Works for me, but we may want to wait for #2016 to go in first. Although, I've left a "hole" for it here so I guess this could go in first.

**Comment by jspahrsummers** [comment]
Either way is fine. I'm happy to manually merge #2016 in to resolve the conflict.

**Comment by neilpa** [comment]
Then lets push this and we can start PRs for each individual page.

**Pull request merged**
