### PR TITLE
Changed the method prefix and class suffix used for swizzling.

### PR DESCRIPTION
**Pull request by andersio**
Fixes https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3269.

### CODE REVIEW

**Comment by sharplet** [comment]
Do you think it would be worth having an integration test for this that pulls in ReactiveObjC?

**Comment by andersio** [comment]
Perhaps ReactiveObjCBridge would be a better place, hmm?

**Comment by sharplet** [comment]
Yeah, I suppose? It is about integration by definition. We'd have to change it to pull in ReactiveCocoa instead of just ReactiveSwift.

**Comment by mdiep** [comment]
I don't think an integration test is necessary here. It's a pretty easy, non-breaking change if this ever breaks again.

**Pull request merged**
