### PR TITLE
Remove no longer needed ‘try!’

### PR DESCRIPTION
**Pull request by klaas**
#### Checklist
- [x] There is no need to updated CHANGELOG.md.

### CODE REVIEW

**Comment by klaas** [comment]
I really would like to understand what failed exactly due to my small change. But I don't get it, because there are so many warnings.

**Comment by klaas** [comment]
Ahhh, seem to be related to https://stackoverflow.com/questions/28794243/xcode-build-fails-with-error-code-65-without-indicative-message

**Comment by klaas** [comment]
Closing and Reopening to trigger a new build

**Comment by klaas** [comment]
Closing and Reopening to trigger a new build

**Comment by andersio** [comment]
Sometimes Xcode is flaky on CI. Thanks for tackling the to-do anyway. 😸

**Pull request merged**
