### PR TITLE
[WIP] Memory corruption

### PR DESCRIPTION
**Pull request by brow**
While working on #2192, I accidentally wrote a test that crashes with memory corruption. In this branch, I'm trying to reduce the crashing test to understand what's going on.

So far, it seems like the prerequisites for the crash include defining a polymorphic, curried function and using `|>` to apply it to a `Signal` or `SignalProducer`. The fact that `a |> f(b)` triggers the crash while `f(b)(a)` does not led me to discover #1953, but I'm not sure yet that this is a `@noescape` issue.

### CODE REVIEW

**Comment by brow** [comment]
The crash has been difficult to isolate because it's not deterministic, but each of the commits on this branch produced a crash in at least one test run.

**Comment by brow** [comment]
The crash still occurs if I revert 99b999509ad1b8647d86e66aa005eb9def0a76c4, so this seems to be a separate issue from #1953.

**Comment by ikesyo** [comment]
We had many crashes related to curried functions in operator definitions. Because of that, we now don't use curried functions anymore to avoid that undeterministic crashes. I belive this is a compiler bug and fixed in Xcode 7/Swift 2 beta.

**Comment by brow** [comment]
@ikesyo That resolves the crash. Thanks!

**Comment by ikesyo** [comment]
@brow No problem!

Ref: #1775(eed1485, 04af6ca, 43808aa), #1824, #1902 and #2032.

**Pull request closed without merging**
