### PR TITLE
Convert to Swift 4.2.

### PR DESCRIPTION
**Pull request by renatorodrigues**
#### Checklist
- [ ] Updated CHANGELOG.md.

## Changes
- [x] Update project language to 4.2
- [x] Update Quick and Nimble
- [x] Update APIs

### CODE REVIEW

**Comment by andrei-kuzma** [comment]
@renatorodrigues, I believe it should compile for old versions of swift too
You should use #if swift(>=4.2) statement for changes
Or probably it would be better to have typealiases for changed types with different values depending on swift version

**Comment by horita-yuya** [comment]
@renatorodrigues 
Thank you. 
I need this update 🙏

**Comment by ikesyo** [comment]
@horita-yuya Since current Swift compiler supports multiple language version mode, you still should be able to  build current RAC 8.0 as is with Xcode 10 (with Swift 4 mode). Why do you **need** this change?

**Comment by horita-yuya** [comment]
Because, building with Swift4.2 mode become an error.

**Comment by ikesyo** [comment]
As you may already understand, you can select Swift language mode for each target independently. So building your app target with Swift 4.2 mode and building other libraries with Swift 4 mode is a valid use case.

**Comment by andrei-kuzma** [comment]
Anyway it would be great to have this update in the nearest future

**Comment by usatie** [comment]
Any update?
I want this PR to be merged to silence the warnings in my project.
I'm using ReactiveCocoa as git submodule.

**Comment by Renatdz** [comment]
Any update?
This PR is stopped for months

**Comment by anayini** [comment]
@renatorodrigues still trying to land this?

**Comment by ikesyo** [comment]
Closing this in favor of #3650. Thanks for the PR though!

**Pull request closed without merging**
