### PR TITLE
accumulate values

### PR DESCRIPTION
**Pull request by ajjnix**
This is can use for accumulate values count. For example I used this code for accumulate locations in trip

### CODE REVIEW

**Comment by mdiep** [comment]
Can you provide some more detail about what you'd use this for?

**Comment by ajjnix** [comment]
Yeah of course. I need observe change location (with complex business logic), after I should get trip from point locations and send it to server. So I accumulate point locations to trip in the required size and send it onward. After that I need continue accumulate NEW trip.

```Swift
        location().accumulate(tripSize).observeNext { [unowned self] locations in
            self.tripObserver.sendNext(locations)
        }
```

**Comment by mdiep** [comment]
I think this makes sense as an operator, but I think it should be called `collect` to match the terminology of the existing operator.

**Comment by dmcrodrigues** [comment]
This operator can be helpful but I would like to suggest a small change to make it more flexible, instead of providing a size to collect the values, I rather prefer having a predicate to control how values should be collected. This predicate can receive the `values` already collected along with the `next` value that may be collected.

```swift
(values: [Value], next: Value) -> Bool
```

With this flexibility, I think we can accomplish both this one as #2815. For this particular case we can use something like: 

```swift
{ values, _ in values.count < someSize }
```

@mdiep @ajjnix @startupthekid I'm attaching an implementation that cover both of them. What do you guys think? I don't think its possible to achieve this with a combination of the existing operators but I can be wrong. I also have some tests if this goes forward.

```swift
public func collect(predicate: (values: [Value], next: Value) -> Bool) -> Signal<[Value], Error> {
    return Signal { observer in
        var values: [Value] = []

        func collectNextValue(value: Value) -> Bool {
            if predicate(values: values, next: value) {
                values.append(value)
                return true
            }
            return false
        }

        func pushCollectedValues() {
            if !values.isEmpty {
                observer.sendNext(values)
                values.removeAll()
            }
        }

        return self.observe { event in
            switch event {
            case let .Next(value):
                if !collectNextValue(value) {
                    sendCollectedValues()
                    // Retry collecting the next value without all values collected...
                    if !collectNextValue(value) {
                        // Value cannot be collected...
                        observer.sendNext([value])
                    }
                }

            case .Completed:
                // Push all remaining values collected
                sendCollectedValues()
                observer.sendCompleted()

            case let .Failed(error):
                observer.sendFailed(error)
            case .Interrupted:
                observer.sendInterrupted()
            }
        }
    }
}
```

**Comment by mdiep** [comment]
That's a great idea. 👍 I was going to suggest we add both a count-based and a predicate-based version to cover this and #2815. Want to open a PR?

(But I'd expect the predicate to return `true` when the values should be sent—not when they should be collected.)

**Comment by dmcrodrigues** [comment]
Sure 👍  But do you think they should be completely independent (in terms of implementation) of each other? Or can we use the predicate-based version as the base to provide a count-based version?

About the predicate makes sense 👍

**Comment by mdiep** [comment]
> Or can we use the predicate-based version as the base to provide a count-based version?

I think both the count-based and the existing version can be based on the predicate version.

**Comment by ikesyo** [comment]
Superseded by #2835.

**Pull request closed without merging**
