### PR TITLE
Add reactive UIScrollView

### PR DESCRIPTION
**Pull request by dcaunt**
- [x] Add `contentInset` binding
- [x] Add `scrollIndicatorInsets` binding
- [x] Add `isScrollEnabled` binding
- [x] Add `zoomScale` binding
- [x] Add `minimumZoomScale` binding
- [x] Add `maximumZoomScale` binding

### CODE REVIEW

**Comment by andersio** [comment]
`isScrollEnabled` and `zoomScale` should be useful. But I am not quite sure about others...

**Comment by dcaunt** [comment]
I think that `contentInset` and `scrollIndicatorInsets` are also as useful – they quite commonly adjusted for keyboard appearance, for example. The min/max zoom scale perhaps not, but they're trivial to implement here.

**Comment by andersio** [comment]
It seems the tests need to be updated for RAS 1.0.0 rc1.

**Comment by dcaunt** [comment]
All green now :)

**Comment by mdiep** [comment]
Thanks!

**Pull request merged**
