### PR TITLE
Tweak kerning of “ct” in the logo

### PR DESCRIPTION
**Pull request by bencochran**
The kerning between the c and t in the logo was still looking a bit off to me. This moves the “c” left 4pts (in the SVG’s coordinate space). I also dumped new PNG assets from the SVGs.

/cc @kaishin:
I wasn’t sure what the source format was, but I edited the SVG by hand to minimize changes then used Sketch to re-export the PNGs. Sound good to you?

### CODE REVIEW

**Comment by kaishin** [comment]
Agreed this looks better. Nice work @bencochran!

Looks merge-able to me!

**Comment by kaishin** [comment]
On a sidenote I'm for keeping the SVG as the canonical file format instead of a proprietary format like PSD of Sketch.

**Comment by NachoSoto** [comment]
:+1: thanks @bencochran & @kaishin!

**Comment by bencochran** [comment]
Thanks for the review, @kaishin. And I’m :+1: on letting SVG be the authoritative source.

Thanks @NachoSoto for the merge!

**Pull request merged**
