### PR TITLE
Swift 2

### PR DESCRIPTION
**Pull request by neilpa**
This PR currently targets **Xcode 7**. It should also work on Xcode 7.1 beta.

Of significant note is that |> is gone. Signal operators are now implemented as protocol extensions so you can use normal dot-method syntax.

----

Continuation of #2088 since the `swift-development` branch has been merged to master

### CODE REVIEW

**Comment by adly-holler** [comment]
@neilpa Looking at the commits, looks like it targets beta 5. Could you update the comment so others don't get misled?

**Comment by neilpa** [comment]
Done

**Comment by adly-holler** [comment]
When I try to build `swift2` for iOS with Carthage and Xcode 7 beta 5 I get `CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.0'`. Xcode 6.4 on 3.0 RC1 works fine. Anyone else seeing this?

**Comment by rpowelll** [comment]
Yep, seeing the exact same issues.

**Comment by neilpa** [comment]
Do you have a developer signing identity? I was just able to successfully build with `carthage bootstrap --no-use-binaries --platform ios`.

```
CodeSign /Users/neilpa/Library/Developer/Xcode/DerivedData/Result-avriscduekfmpuekilrdpenmiuca/Build/Products/Release-iphoneos/Result.framework
    cd /Users/neilpa/code/contrib/RAC4/Carthage/Checkouts/Result
    export CODESIGN_ALLOCATE=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
      
Signing Identity:     "iPhone Developer: Neil Pankey (*************)"

    /usr/bin/codesign --force --sign ************************************** --timestamp=none /Users/neilpa/Library/Developer/Xcode/DerivedData/Result-avriscduekfmpuekilrdpenmiuca/Build/Products/Release-iphoneos/Result.framework

** BUILD SUCCEEDED **
```

**Comment by adly-holler** [comment]
I do have a developer signing identity and changing the top-level, root `Code Signing Identity` for the iOS Framework Target fixed the problem

**Comment by rpowelll** [comment]
Yep, I have a code signing identity, I haven't encountered this issue in older versions.

**Comment by neilpa** [comment]
Probably an Xcode fail. I've had to toggle/sync/refresh/etc signing identities in the project properties before and that seems to magically fix things.

**Comment by adly-holler** [comment]
Resolved it like this: https://github.com/ReactiveCocoa/ReactiveCocoa/compare/swift2...Tripstr:swift2-fix-codesign

**Comment by neilpa** [comment]
That shouldn't be needed because of the line right below it `"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";`

**Comment by neilpa** [comment]
Actually, I bet it's failing for watchOS builds so we'll need a similar signing identity setting. That would also explained why it worked for me without any issue when I used `--platform ios` to scope the build.

**Comment by adly-holler** [comment]
I used `--platform iOS` as well

**Comment by adly-holler** [comment]
@neilpa Mind updating the comment for Beta 6? Also I'm still seeing the same Carthage build error on the iOS platform unless I manually set `iOS Developer` as the top-level signing identity for the project
screen shot 2015-08-25 at 11 33 29 am

**Comment by rpowelll** [comment]
@neilpa: watchOS builds work fine without code signing, but I've been unable to get ReactiveCocoa building without changing the signing identities as in #2292

**Comment by Gurpartap** [comment]
Was the codesign issue supposed to have been fixed? I'm asking because I'm still having the above discussed issue with swift2 HEAD from today using `--platform iOS` (I didn't try without it). Adding `--no-use-binaries` lets it compile.

**Comment by neilpa** [comment]
Something is definitely still weird with code-signing. I suspect it has to do with nested framework dependencies. I was trying to update [Rex](https://github.com/neilpa/rex/tree/swift2) and hit the code sign error if I use 5e75726. I'm going to see if I can track this down...

**Comment by bencochran** [comment]
I believe the remaining issue may be related to https://github.com/Carthage/Carthage/issues/418 ([associated radar](http://www.openradar.me/20490378)). I’m noticing that even if I specify `--platform iOS`, my codesign error happens on:

> === BUILD TARGET Result-watchOS OF PROJECT Result WITH CONFIGURATION Release ===

**Comment by 0xpablo** [comment]
Maybe we could set dependencies explicitly (an option in the build section of the scheme editor) so the problem goes away until Apple fixes this. 
The `xcodebuild` bug only appears when dependencies are found implicitly.

**Comment by Gurpartap** [comment]
Even `--no-use-binaries` doesn't help any more with Xcode 7 GM and current swift2 HEAD.

`carthage bootstrap --no-use-binaries --platform iOS`

```
...
** BUILD SUCCEEDED **

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos9.0

=== BUILD TARGET Result-watchOS OF PROJECT Result WITH CONFIGURATION Release ===

Check dependencies
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.0'
```

**Comment by iv-mexx** [comment]
@Gurpartap I managed to circumvent this error by closing Xcode before running carthage: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2319#issuecomment-139199127

**Comment by Gurpartap** [comment]
@iv-mexx Thanks! :+1:

**Comment by NachoSoto** [comment]
Should we merge this into `master` already? :)

**Comment by NachoSoto** [comment]
Is anyone opposed to merging this into `master` already and making a new `alpha.2` release?

**Comment by neilpa** [comment]
> Is anyone opposed to merging this into master already and making a new alpha.2 release?

As long as we don't delete this branch right away. There's still open PRs against this branch that we be painful to restart. Once they're in we can delete it.

**Comment by NachoSoto** [comment]
> As long as we don't delete this branch right away. There's still open PRs against this branch that would be annoying to reopen. Once they're merged we can send them to master and delete the branch.

We can leave the branch, it should be easy to re-target the PRs before merging them.

**Comment by neilpa** [comment]
> We can leave the branch, it should be easy to re-target the PRs before merging them.

I'd like to avoid that and do a second merge of the `swift2` branch after we cut alpha 2 off `master`. Specifically, I'd like to hold off on #2360 and make that part of an alpha 3.

**Comment by NachoSoto** [comment]
:+1:

**Comment by neilpa** [comment]
Merging this to `master` before I cut the alpha 2 release.

**Comment by NachoSoto** [comment]
:heart:

**Comment by Gurpartap** [comment]
✌️

**Pull request merged**
