### PR TITLE
Always use code signing for iOS target

### PR DESCRIPTION
**Pull request by rpowelll**
This fixes an issue that would arise when trying to use the framework with Carthage, as brought up in #2189

### CODE REVIEW

**Comment by JaviSoto** [comment]
Yeah, I had this issue as well. I was patching it locally while I figured out if there was a reason for it to be the way it is, but I don't know :D 

I'll wait for another contributor to give the thumbs up, but this looks good to me :+1:

**Comment by neilpa** [comment]
I was also hoping for someone more versed in the nuances of code signing would chime in which is why I hadn't merged it yet.

**Comment by rpowelll** [comment]
Yeah this solution doesn't seem ideal. I'd love some input from someone more knowledgeable on the topic, but I thought it made sense to open this PR to give the issue some more visibility.

**Comment by NachoSoto** [comment]
I'm afraid to call myself "versed in the nuances of code signing", but I'm willing to say this diff looks correct.

**Comment by neilpa** [comment]
I'll go ahead and merge this then, especially since this is still a beta branch (even though I think a fair number of people are using it).

**Comment by rpowelll** [comment]
:rocket:

**Pull request merged**
