### PR TITLE
then should be available for NoError

### PR DESCRIPTION
**Pull request by Igor-Palaguta**

### CODE REVIEW

**Comment by mdiep** [comment]
Could you also handle the case where the new signal has `NoError`?

That requires adding 2 more variants, just like `flatMap`, because you need to add one where both signals are `NoError`—otherwise it's ambiguous for those signals.

**Comment by NachoSoto** [comment]
:ship it: after @mdiep's comment. That also shows that this need an extra test to cover the ambiguity.

**Comment by Igor-Palaguta** [comment]
Please check

**Comment by mdiep** [comment]
Looks good (although it's curious that you didn't need a 3rd overload; maybe this is changed in Swift 3).

Just waiting on CI. Travis is a bit backed up due to maintenance, so it may be a while longer.

**Comment by mdiep** [comment]
Thanks for the pull request! 🎉

**Pull request merged**
