### PR TITLE
Use class name, not dynamicType

### PR DESCRIPTION
**Pull request by ikesyo**
Because this is final class.

### CODE REVIEW

**Comment by JaviSoto** [comment]
Yeah, this makes sense to me. Any reason why it may have used `dynamicType` in the first place?

**Comment by neilpa** [comment]
@JaviSoto I suspect leftovers from the earlier Swift betas.

**Comment by JaviSoto** [comment]
That would make sense. I will defer this to somebody else to merge, I want to make sure I'm not missing something here :)

**Comment by jspahrsummers** [comment]
This was basically just to avoid duplicating the class name unnecessarily, but it seems too obfuscated and not that big a deal. :+1: on merging.

**Pull request merged**
