### PR TITLE
Swift 3.0 Groundwork

### PR DESCRIPTION
**Pull request by andersio**
Originally #3001. It now bases on `master` (4.x) without all the shiny features `RAC5` has.

-
A few special notes:

1. Implemented #2926.
    But `timer(_: onScheduler:withLeeway:)` is instead renamed to `SignalProducer<Date, NoError>(interval:on:leeway:)`. It is a compromise made for the type inferrer, since even if the static function does not use any associated types, the inferrer would still do its work. The original form is marked `@unavailable`.

7. `Action(enabledIf:_:)` is renamed to `Action(enabling:_:)`.
The rationale here is that `enabling` gives a sense of action (to enable something), versus the status represented by `enabled`. (Should we call it a `switch` instead? Or just revert it?)

4. Operators are still imperative verbs.
Since the discussion of naming conventions on swift-evolution is still on-going, we should perhaps delay stuffing/renaming _operators_ to a future PR, as suggested by various contributors on the channel.

4. Closure arguments aren't named yet.
Same situation as (4).

### CODE REVIEW

**Comment by andersio** [comment]
Kind of inspired by #3024, I would suggest bringing back `sink` (or `inputObserver` if you prefer) as the parameter name for input observers, i.e. signal generator & producer start handler. This bugs me for a while when writing documentations, since `observer` in these contexts has a different role than the observers supplied to `start` or `observe`.

**Comment by mdiep** [comment]
I'm not ready to accept these changes on `master`, since want to ship another 4.x release with Swift 2.2/2.3 support.

It would be better to target this against the RAC5 branch IMO since these changes are for RAC5. Otherwise we can discuss this here but wait to merge until the RAC5 branch has been merged.

**Comment by andersio** [comment]
@mdiep Would you consider rebasing `RAC5` on top of this branch? Say at least we may provide a stopgap version/branch with no breaking changes, in case we do not release `RAC5` in line with Swift 3.

**Comment by mdiep** [comment]
No, I plan to release RAC5 in line with Swift 3. (It necessarily needs to be a major version because it's a breaking change.)

I think reviving the old PR is a better idea.

**Pull request closed without merging**
