### PR TITLE
Added operations not, and, or to SignalProducerType

### PR DESCRIPTION
**Pull request by mpurland**

### CODE REVIEW

**Comment by neilpa** [comment]
Thanks for the PR. However, as standalone signal operators these aren't that useful. Generally you'll already have `map` block you can incorporate this logic into. 

I'm experimenting with similar ideas for boolean properties which could get rolled into RAC if they prove useful. c.f. neilpa/Rex#48.

**Comment by mpurland** [comment]
@neilpa I like the idea. It would be nice if those predicate properties init allowed inclusion of their SignalProducer counterparts. 

Is the idea going forward to only improve existing `core` functionality in ReactiveCocoa but leave other operations to extension frameworks?

**Comment by neilpa** [comment]
> Is the idea going forward to only improve existing core functionality in ReactiveCocoa but leave other operations to extension frameworks?

Not strictly, but we don't want to add new operators that increase the API surface when they can easily be achieved with existing operators.

**Comment by neilpa** [comment]
> @neilpa I like the idea. It would be nice if those predicate properties init allowed inclusion of their SignalProducer counterparts.

I've got a few ideas to improve that PR, just haven't gotten around to it yet.

**Comment by NachoSoto** [comment]
> Not strictly, but we don't want to add new operators that increase the API surface when they can easily be achieved with existing operators.

Especially when the focus is on getting RAC ~~3~~4 stable :)

**Comment by mpurland** [comment]
> Especially when the focus is on getting RAC 34 stable :)

I would love to help with that. What needs attention?

**Comment by NachoSoto** [comment]
We're tracking that [here](https://github.com/ReactiveCocoa/ReactiveCocoa/milestones/4.0). There's really only one major thing blocking: #2453 (and maybe #2360)

**Comment by neilpa** [comment]
I'd also add waiting for Xcode 7.1 to GM in case it requires more breaking changes. I don't want to be forced to release a 5.0 anytime soon.

**Comment by NachoSoto** [comment]
That's out already :)

**Comment by neilpa** [comment]
Oh, it was still 7.0 in the appstore a few days ago. I haven't kept on top of these things as much lately.

**Pull request closed without merging**
