### PR TITLE
Implement Action.apply

### PR DESCRIPTION
**Pull request by jspahrsummers**
And with a simpler synchronization model than the [previous implementation](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/e62d03d2610e5b7615e442b60bf49104dd4cb3da/ReactiveCocoa/Swift/Action.swift#L46-L55)!

### CODE REVIEW

**Comment by joshaber** [comment]
Needs a merge :pray:

**Comment by jspahrsummers** [comment]
Resolving that merge conflict necessitated the new `ActionError` type here, so this PR has expanded a little bit in scope.

**Comment by joshaber** [comment]
:cool:

**Pull request merged**
