### PR TITLE
Update ReactiveCocoa.podspec [4.0.0-rc.2]

### PR DESCRIPTION
**Pull request by AYastrebov**
- point to 4.0.0-rc.2
- in addition to #3601

#### Checklist
- [x] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by mdiep** [comment]
CI is failing, but I don't see why 😕

**Comment by ikesyo** [comment]
> The command "XCODE_SCHEME=ReactiveCocoa-macOS XCODE_SDK=macosx XCODE_ACTION="build test" XCODE_DESTINATION="arch=x86_64" XCODE_PLAYGROUND_TARGET="x86_64-apple-macosx10.10" PLAYGROUND="ReactiveCocoa-macOS.playground" script/build" exited with 65.

**Comment by AYastrebov** [comment]
@mdiep @ikesyo I've run tests on my repo and it's all green. Can you run the tests again?

**Comment by ikesyo** [comment]
Just restarted.

**Pull request merged**
