### PR TITLE
Rename join/joinMap to flatten/flatMap

### LINKED ISSUE #1842: Rename joinMap to flatMap for stdlib consistency?
`joinMap` predates `flatMap` in the stdlib, but maybe it's worth renaming it to be consistent now.

We would still have our `strategy` parameter, which makes it a little different, but it would at least highlight the parallels.

Thoughts?

### PR DESCRIPTION
**Pull request by jspahrsummers**
Resolves #1842.

Unfortunately, as you can see, this breaks the symmetry we had with `join{,Map}`, but I think the consistency with the standard library is worth it.

This is hopefully the last _major_ breaking change in RAC 3—if we even decide to accept it. :open_hands:

### CODE REVIEW

**Comment by kastiglione** [comment]
Too bad we can't open a pull request to bring "to flat" into english as a verb.

**Comment by neilpa** [comment]
:+1: for consistency with the stdlib here.

**Comment by jspahrsummers** [comment]
I'm still ambivalent, so I'd like @joshaber to make the final call here.

**Comment by joshaber** [comment]
I go back and forth. I think there's probably only 4.39 people in the world who understand how this `flatMap` would relate to Swift's stdlib `flatMap` so I'm not sure that's a compelling reason. And I think it's confusing for those used to `flatMap` from RAC 2.

**Comment by joshaber** [comment]
Unless anyone has a compelling argument for changing it, :-1:

**Comment by jspahrsummers** [comment]
I'm not strongly in favor of `flatMap` (mostly because of the inconsistency in `flatten`), but I do think it's a mildly better name.

`join` doesn't build any intuition or convey what it means to perform the operation. At best, it sounds like “joining a thread,” which isn't really an accurate mental model. But _flattening_ at least implies that you're taking a complicated structure and “flattening it out,” even if it's not exactly clear how that happens.

`-flattenMap:` was a poor name for the operation in RAC 2 that is better known as “merge,” and I don't think we should be constrained by our past mistakes—especially with the strategy argument it has (that can't be omitted), which will make it clear that only _one_ version matches the previous behavior.

**Comment by joshaber** [comment]
>join doesn't build any intuition or convey what it means to perform the operation. At best, it sounds like “joining a thread,” which isn't really an accurate mental model.

Legit :+1:

**Pull request merged**
