### PR TITLE
Hardcode the framework name to fix issues arising from #2398

### PR DESCRIPTION
**Pull request by tonyarnold**
So the "feature" in Xcode that made my "fix" in #2398 was fixed in Xcode 7.1. 

Come at me bro

Yes, I should have hardcoded this from the start. Come at me.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Would the default from the `xcconfig` (project name) work now?

**Comment by tonyarnold** [comment]
:point_up: yes :grinning:

**Comment by NachoSoto** [comment]
Awesome!

**Comment by neilpa** [comment]
> Would the default from the xcconfig (project name) work now?

This doesn't seem to work. Each time I open the project Xcode is automatically renaming the `BuildableName` property in the schemes to just `.xctest`

```patch
diff --git a/ReactiveCocoa.xcodeproj/xcshareddata/xcschemes/ReactiveCocoa-Mac.xcscheme b/ReactiveCocoa.xcodeproj/xcshareddata/xcschemes/ReactiveCocoa-Mac.xcscheme
index acf45a1..fb27c56 100644
--- a/ReactiveCocoa.xcodeproj/xcshareddata/xcschemes/ReactiveCocoa-Mac.xcscheme
+++ b/ReactiveCocoa.xcodeproj/xcshareddata/xcschemes/ReactiveCocoa-Mac.xcscheme
@@ -29,7 +29,7 @@
             <BuildableReference
                BuildableIdentifier = "primary"
                BlueprintIdentifier = "D04725F419E49ED7006002AA"
-               BuildableName = "ReactiveCocoa.xctest"
+               BuildableName = ".xctest"
                BlueprintName = "ReactiveCocoa-MacTests"
                ReferencedContainer = "container:ReactiveCocoa.xcodeproj">
             </BuildableReference>
@@ -48,7 +48,7 @@
```

**Comment by tonyarnold** [comment]
Yeah, the test targets have no PRODUCT_NAME. Looks like the xcconfigs don't specify anything — I'll hardcode those guys — doesn't matter if they're named differently per-platform.

**Comment by tonyarnold** [comment]
I've just pushed a fix for the test targets, and a couple of other minor issues. Can we just reopen this PR, or do I need to make a new one?

**Pull request merged**
