### PR TITLE
Bump SPM swift-tools-version to 5.2

### PR DESCRIPTION
**Pull request by mluisbrown**
For the same reason as this was done in ReactiveSwift, which is so that test dependencies aren't exposed to clients of this package.

### CODE REVIEW

**Comment by andersio** [comment]
Could you update `.swift-version` too?

**Comment by mluisbrown** [comment]
@andersio  Done 👍

**Comment by mluisbrown** [comment]
This test is failing on macCatalyst:

```
it("should accept changes from bindings to its zoom enabled state")
```

No idea why 🤷

**Comment by andersio** [comment]
MapKit tests sometimes fail because MapKit intermittently retains the views a little longer.

**Pull request merged**
