### PR TITLE
Re-added tvOS scheme

### PR DESCRIPTION
**Pull request by NachoSoto**
Reverts ReactiveCocoa/ReactiveCocoa#2359

This is incompatible with Xcode 7, so we need to wait until 7.1 is GM.

### CODE REVIEW

**Comment by neilpa** [comment]
Probably want a branch for this and any other Xcode 7.1 changes to live in for the time being.

**Comment by NachoSoto** [comment]
Yeah, `revert-2359-revert-tvOS` for now. If I or anyone else needs to add any more commits we can copy it to another branch with a better name.

**Comment by NachoSoto** [comment]
@gfontenot @neilpa now it's here :)

**Comment by NachoSoto** [comment]
Reopened in #2502

**Pull request closed without merging**
