### PR TITLE
Deprecate SignalProducer.buffer()

### PR DESCRIPTION
**Pull request by mdiep**
cf. #2831

I want to get better at deprecating these things to make upgrading easier.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Awesome :shipit:

**Comment by eimantas** [comment]
There should probably be "use this instead:" note.

**Comment by NachoSoto** [comment]
@eimantas it says that on the message :)

**Comment by eimantas** [comment]
Right. Let me get my coffee...

**Pull request merged**
