### PR TITLE
[RFC] Add type-safe method lifting with weak reference semantics

### PR DESCRIPTION
**Pull request by sharplet**
This is a potential improvement I'd like to submit for review as part of #2535.

---

### Overview: `Method` and `MethodType`

This change introduces a new `MethodType` protocol and concrete `Method` class. A `Method` encapsulates a weak reference to an object, and a function that accepts a reference to the object, some input, and returns the method's output.

When a `Method` is lifted using a signal or signal producer of input, it returns a signal or signal producer (respectively) of output from the results of calling the function with the input.

If the weakly-referenced object is deallocated, the lifted signal or signal producer will send an interrupted event. When the Objective-C runtime is present, this is achieved by observing the object's deallocation at runtime. There is a fallback implementation for native Swift objects: even though it's impossible to be notified when a weakly-referenced Swift object is deallocated, we can wait until the next input value is sent and lazily interrupt the signal if the result of the method call is `nil`.

---

### Also: Even better bindings?

The changes as they are right now are not the end goal: I'd also like to add support for the `<~` operator, and create a unifying `Bindable` protocol that both `MethodType` and `MutablePropertyType` would conform to. This would mean that the same set of overloads would work for both kinds of bindable things. Just spitballing here, but this might look something like:

```swift
func <~ <Target: Bindable>(target: Target, signal: Signal<Target.Input, NoError>) -> Disposable
func <~ <Target: Bindable>(target: Target, producer: SignalProducer<Target.Input, NoError>) -> Disposable
// etc.
```

And then in use, you might end up with something like this:

```swift
RAC(refreshControl, UIRefreshControl.endRefreshing) <~ feedController.feedRefresh
RAC(tableView, UITableView.reloadData) <~ feedController.feedRefreshed
```

Also, `Method` solves the "I shouldn't have to set up KVO to bind to a property" problem:

```swift
extension UIImageView {
  var rac_setImage: Method<UIImageView, UIImage, Void> {
    return Method(object: self) { $0.image = $1 }
  }
}

// ...
imageView.rac_setImage <~ viewModel.image
```

---

I plan to push up more comments fleshing these other features out.

Would love to hear your thoughts!

### CODE REVIEW

**Comment by mdiep** [comment]
> When the Objective-C runtime is present, this is achieved by observing the object's deallocation at runtime. There is a fallback implementation for native Swift objects: even though it's impossible to be notified when a weakly-referenced Swift object is deallocated, we can wait until the next input value is sent and lazily interrupt the signal if the result of the method call is nil.

My initial thought is that I'm hesitant to add features that more-or-less depend on Objective-C right now. Given our plan to split this repo up (#2807), I don't think it's a great time to evaluate the potential of a feature like this.

**Comment by sharplet** [comment]
Thanks for the heads-up about the repo splitting, I wasn't aware! Do you think it would be worth adding a note about the roadmap to CONTRIBUTING.md, or perhaps even in an issue or pull request template?

> My initial thought is that I'm hesitant to add features that more-or-less depend on Objective-C right now.

FWIW, I still think there's some value to the idea even without Objective-C—I kind of see `lift()` as a safer version of `map()` that adds the notion of object lifetime. UI bindings that can be torn down automatically (without explicit `Disposable` juggling) are then an obvious use-case of the feature.

**Comment by sharplet** [comment]
Just FYI, I've pushed a version of the `Bindable` protocol I mentioned. That should complete all of the functionality I described.

**Comment by mdiep** [comment]
Thanks for the pull request, but I don't think this is a good fit for the RAC core. Unfortunately, I don't really have any concrete feedback for you.

But I will say that your last example, `imageView.rac_setImage <~ viewModel.image`, is something that we would use `MutableProperty` for.

**Comment by sharplet** [comment]
Ok, thanks for considering it. There was a problem this was solving for me, what's the best forum to discuss solving the problem in a different way? I could perhaps raise an issue with a more concrete example?

**Comment by mdiep** [comment]
> There was a problem this was solving for me, what's the best forum to discuss solving the problem in a different way? I could perhaps raise an issue with a more concrete example?

💯 this.

A better understanding of the issue might lead to (a) reconsideration of this PR or (b) a better solution. 😄

**Comment by sharplet** [comment]
I opened an issue: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2946.

**Pull request closed without merging**
