### PR TITLE
Turn travis back on

### LINKED ISSUE #1823: Re-add .travis.yml once Swift 1.2 is out of beta
This file was removed in #1775 due to lack of Travis support.

h/t @neilpa

### PR DESCRIPTION
**Pull request by neilpa**
http://blog.travis-ci.com/2015-05-26-xcode-63-beta-general-availability/

Resolves #1823

### CODE REVIEW

**Comment by NachoSoto** [comment]
Woot! Will this work? 
skeptical

**Comment by neilpa** [comment]
The build is "pending" so we'll see.

**Comment by NachoSoto** [comment]
(I can't wait to have this either way, but: ) looks like tests are being compiled with `-Onone`. I'm going to check if they even pass with `-O`...

**Comment by jspahrsummers** [comment]
@NachoSoto The Test action (not to be confused with the Test configuration—long story) should be using `-O`.

**Comment by NachoSoto** [comment]
@jspahrsummers 
screen shot 2015-05-26 at 18 19 31

Oh I see!

**Comment by jspahrsummers** [comment]
@neilpa The build that failed is probably caused by a race condition. Could you make the test more conservative so it's not at risk of failing again in the future?

We probably won't be modifying the legacy APIs much anyways, so I'm okay making the test marginally less exhaustive.

**Comment by neilpa** [comment]
I doubled the time, although I wouldn't be surprised if this still fails again in the future. I'm always dubious of automated tests using real time on likely throttled VMs.

**Pull request merged**
