### PR TITLE
Fix `SignalProducer(values: Value...)` signature to be distinguished from `SignalProducer(values: S)`

### PR DESCRIPTION
**Pull request by ikesyo**
https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3037#issuecomment-231132459

### CODE REVIEW

**Comment by NachoSoto** [comment]
Oooh very clever. Could you add @mdiep's example as a test case to make sure we never break this ambiguity again?

**Comment by mdiep** [comment]
👏🏻

**Comment by NachoSoto** [comment]
@RuiAAPeres this wasn't finished! :( We should add a test case for this.

**Comment by NachoSoto** [comment]
Friendly reminder to watch out for other people's comments on a review to make sure things don't get merged prematurely.

**Comment by RuiAAPeres** [comment]
@NachoSoto 😕 sorry. Yeah there is the missing test.

**Pull request merged**
