### PR TITLE
Add `DebugSinkOf`

### PR DESCRIPTION
**Pull request by norio-nomura**
Xcode debugger can't step into `SinkType.put()`.
Using `DebugSinkOf` instead of `SinkOf` allow step into `SinkType.put()`

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Can you please clarify why stepping into `put` is helpful? You should still have a backtrace from whatever `put` does, right?

**Comment by norio-nomura** [comment]
Stepping into `put` does not step into the codes that will be called by `put`.
This behavior forced me to guess what is wrapped inside the `SinkOf`, set breakpoint at guessed place, and was happy with hitting the breakpoint or was sad with never hitting it.
Those steps may be easy if I knew all of ReactiveCocoa, but I don't.
`DebugSinkOf` help it by using "Step into" on debugger.

I think It will be helpful for debugging multi thread event handling.
Break point will stop on all thread whether the thread is currently focusing context or not.
`Step into` does not need breakpoint to following code execution flow.

Yes, It may be helpful just for me.
I didn't know that ReactiveCocoa will need easiness for newbie such as me.
So I just send this PR.
Thanks,

**Comment by jspahrsummers** [comment]
Makes sense.

I'm curious, though, if you step into `put` (into the disassembly), but keep stepping, will it eventually get to a stack frame with actual code? The implementation of `put` doesn't have source code available, but I'm hoping you would see code once it gets to the actual callee.

**Comment by norio-nomura** [comment]
Sorry, I can't understand what are you asking because of my poor english :cry: 

I put some codes for checking generated codes between `SinkOf` and `DebugSinkOf` at [here](https://github.com/norio-nomura/DebugSinkOf).
As I tested, `SinkOf.put()` and `DebugSinkOf.put()` are compiled into direct calling sinked function on `-O`.

Generated SIL from using `SinkOf` code is [here](https://github.com/norio-nomura/DebugSinkOf/blob/master/non-debug-O.sil#L42-L57) as following:
```sil
  %17 = alloc_ref $Counter                        // users: %20, %22, %23
  %18 = integer_literal $Builtin.Int64, 0         // user: %19
  %19 = struct $Int (%18 : $Builtin.Int64)        // user: %21
  %20 = ref_element_addr %17 : $Counter, #Counter.number // user: %21
  store %19 to %20 : $*Int                        // id: %21
  %22 = class_method %17 : $Counter, #Counter.update!1 : Counter -> (Int) -> () , $@cc(method) @thin (Int, @owned Counter) -> () // user: %23
  %23 = partial_apply %22(%17) : $@cc(method) @thin (Int, @owned Counter) -> () // users: %25, %30, %31
  // function_ref reabstraction thunk helper from @callee_owned (@unowned Swift.Int) -> (@unowned ()) to @callee_owned (@in Swift.Int) -> (@unowned ())
  %24 = function_ref reabstraction thunk helper from @callee_owned (@unowned Swift.Int) -> (@unowned ()) to @callee_owned (@in Swift.Int) -> (@unowned ()) : $@thin (@in Int, @owned @callee_owned (Int) -> ()) -> () // user: %25
  %25 = partial_apply %24(%23) : $@thin (@in Int, @owned @callee_owned (Int) -> ()) -> () // user: %26
  %26 = struct $SinkOf<Int> (%25 : $@callee_owned (@in Int) -> ()) // user: %27
  store %26 to %16 : $*SinkOf<Int>                // id: %27
  %28 = integer_literal $Builtin.Int64, 128       // user: %29
  %29 = struct $Int (%28 : $Builtin.Int64)        // user: %31
  strong_retain %23 : $@callee_owned (Int) -> ()  // id: %30
  %31 = apply %23(%29) : $@callee_owned (Int) -> ()
```

Generated SIL from using `DebugSinkOf` code is [here](https://github.com/norio-nomura/DebugSinkOf/blob/master/debug-O.sil#L42-L57) as following:
```sil
  %17 = alloc_ref $Counter                        // users: %20, %22, %23
  %18 = integer_literal $Builtin.Int64, 0         // user: %19
  %19 = struct $Int (%18 : $Builtin.Int64)        // user: %21
  %20 = ref_element_addr %17 : $Counter, #Counter.number // user: %21
  store %19 to %20 : $*Int                        // id: %21
  %22 = class_method %17 : $Counter, #Counter.update!1 : Counter -> (Int) -> () , $@cc(method) @thin (Int, @owned Counter) -> () // user: %23
  %23 = partial_apply %22(%17) : $@cc(method) @thin (Int, @owned Counter) -> () // users: %25, %30, %31
  // function_ref reabstraction thunk helper from @callee_owned (@unowned Swift.Int) -> (@unowned ()) to @callee_owned (@in Swift.Int) -> (@unowned ())
  %24 = function_ref reabstraction thunk helper from @callee_owned (@unowned Swift.Int) -> (@unowned ()) to @callee_owned (@in Swift.Int) -> (@unowned ()) : $@thin (@in Int, @owned @callee_owned (Int) -> ()) -> () // user: %25
  %25 = partial_apply %24(%23) : $@thin (@in Int, @owned @callee_owned (Int) -> ()) -> () // user: %26
  %26 = struct $DebugSinkOf<Int> (%25 : $@callee_owned (@in Int) -> ()) // user: %27
  store %26 to %16 : $*DebugSinkOf<Int>           // id: %27
  %28 = integer_literal $Builtin.Int64, 128       // user: %29
  %29 = struct $Int (%28 : $Builtin.Int64)        // user: %31
  strong_retain %23 : $@callee_owned (Int) -> ()  // id: %30
  %31 = apply %23(%29) : $@callee_owned (Int) -> ()
```

Full diff is [here](https://github.com/norio-nomura/DebugSinkOf/blob/master/diff-between-non-debug-O-and-debug-O.diff)

**Comment by jspahrsummers** [comment]
Sorry for being unclear!

What I mean is: `put` can't be stepped into (as you've pointed out), but can you step _through_ it and get to the function that it eventually calls? If you can do that, then it doesn't matter if its source code is unavailable.

**Comment by norio-nomura** [comment]
Thank you for writing easily :smile:

I understand.
I just tried to *Step Into* in disassembly view as following:
1. On Xcode, check Debug > Debug Workflow > Always Show Disassembly
2. Set breakpoint at `sink.put(.complete)` in Event.swift
3. Run and hit the breakpoint.
4. Hit `F7`(Step Into)
5. It fail. The debugger skips to next line of `Event.swift` and shows disassembly of that line. :disappointed: 
I also tried to using  disassembly of Assistant Editor and failed.

Another method:
1. Add Symbolic breakpoint `Swift.SinkOf.put` and disable it
2. Set breakpoint at `sink.put(.complete)` in Event.swift
3. Run and hit the breakpoint of 2
4. Enable breakpoint of 1, disable of 2
5. Hit `F7`(Step Into)
6. Then stopped inside of `Swift.SinkOf.put`, disable breakpoint of 1 for another thread.
7. Continue stepping by hitting `F6` (Step Over).
*In disassembly, every step needs 5sec on my MacBook Pro (Retina, 13-inch, Late 2013) 2.6 GHz Intel Core i5*
```asm
libswiftCore.dylib`Swift.SinkOf.put <A>(Swift.SinkOf<A>)(A) -> ():
->  0x100707110 <+0>:  pushq  %rbp
    0x100707111 <+1>:  movq   %rsp, %rbp
    0x100707114 <+4>:  movq   %rsi, %rax
    0x100707117 <+7>:  movq   %rdx, %rsi
    0x10070711a <+10>: popq   %rbp
    0x10070711b <+11>: jmpq   *%rax
    0x10070711d <+13>: nopl   (%rax)
```
`jmpq` goes following:
```asm
ReactiveCocoa`partial apply forwarder for reabstraction thunk helper <T_0_0, T_0_1 where T_0_1: ReactiveCocoa.ErrorType> from @callee_owned (@owned ReactiveCocoa.Event<T_0_0, T_0_1>) -> (@unowned ()) to @callee_owned (@in ReactiveCocoa.Event<T_0_0, T_0_1>) -> (@unowned ()):
->  0x1004324b0 <+0>:   pushq  %rbp
    0x1004324b1 <+1>:   movq   %rsp, %rbp
    0x1004324b4 <+4>:   subq   $0x50, %rsp
    0x1004324b8 <+8>:   movq   0x10(%rsi), %rax
    0x1004324bc <+12>:  movq   %rax, -0x8(%rbp)
    0x1004324c0 <+16>:  movq   0x18(%rsi), %rcx
    0x1004324c4 <+20>:  movq   %rcx, -0x10(%rbp)
    0x1004324c8 <+24>:  movq   0x20(%rsi), %r9
    0x1004324cc <+28>:  movq   0x28(%rsi), %rdx
    0x1004324d0 <+32>:  movq   0x30(%rsi), %r8
    0x1004324d4 <+36>:  movq   %rdi, -0x18(%rbp)
    0x1004324d8 <+40>:  movq   %r8, %rdi
    0x1004324db <+43>:  movq   %r8, -0x20(%rbp)
    0x1004324df <+47>:  movq   %rsi, -0x28(%rbp)
    0x1004324e3 <+51>:  movq   %rax, -0x30(%rbp)
    0x1004324e7 <+55>:  movq   %rcx, -0x38(%rbp)
    0x1004324eb <+59>:  movq   %r9, -0x40(%rbp)
    0x1004324ef <+63>:  movq   %rdx, -0x48(%rbp)
    0x1004324f3 <+67>:  callq  0x1004c0dbe               ; symbol stub for: swift_retain_noresult
    0x1004324f8 <+72>:  movq   -0x28(%rbp), %rdi
    0x1004324fc <+76>:  callq  0x1004c0db2               ; symbol stub for: swift_release
    0x100432501 <+81>:  movq   -0x18(%rbp), %rdi
    0x100432505 <+85>:  movq   -0x48(%rbp), %rsi
    0x100432509 <+89>:  movq   -0x20(%rbp), %rdx
    0x10043250d <+93>:  movq   -0x30(%rbp), %rcx
    0x100432511 <+97>:  movq   -0x38(%rbp), %r8
    0x100432515 <+101>: movq   -0x40(%rbp), %r9
    0x100432519 <+105>: addq   $0x50, %rsp
    0x10043251d <+109>: popq   %rbp
    0x10043251e <+110>: jmp    0x100428510               ; reabstraction thunk helper <T_0_0, T_0_1 where T_0_1: ReactiveCocoa.ErrorType> from @callee_owned (@owned ReactiveCocoa.Event<T_0_0, T_0_1>) -> (@unowned ()) to @callee_owned (@in ReactiveCocoa.Event<T_0_0, T_0_1>) -> (@unowned ()) at Event.swift
```
Let's continue 5sec step until the code that wrapped into `SinkOf`… :sweat:

**Comment by jspahrsummers** [comment]
Ah, okay. Thank you for investigating so thoroughly! :sparkles:

One final question: if this type is made `private`, can it still be debugged? I don't want it to be `public` unless necessary.

**Comment by norio-nomura** [comment]
Some APIs expose `SinkOf`. Those will be needed to change using `SinkType`. I'll see them later.

**Comment by norio-nomura** [comment]
Some functions and methods can be change to using `SinkType`.
But `SinkOf` is used in some `public typealias`es and replacing them is hard. :disappointed: 
I consider declaring as following:
```swift
#if DEBUG
public struct SinkOf<T> : SinkType {
	typealias Element = T
	
	let putElement: (T) -> ()
	
	/// Construct an instance whose `put(x)` calls `putElement(x)`
	public init(_ putElement: (T) -> ()) {
		self.putElement = putElement
	}
	
	/// Construct an instance whose `put(x)` calls `base.put(x)`
	public init<S : SinkType where S.Element == T>(var _ base: S) {
		self.putElement = {base.put($0)}
	}
	
	/// Write `x` to this sink.
	public func put(x: T) {
		putElement(x)
	}
}
#else
typealias SinkOf = Swift.SinkOf
#endif
```
for hiding `DebugSinkOf`.
But it will cause ambiguity on projects using RAC, so it may be not good. :disappointed: 
I'm almost giving up.

**Comment by norio-nomura** [comment]
I had confused with ReactiveTask and Carthage. Those should be considered separately.
`DebugSinkOf` needs same access level of `Signal.Observer`.

**Comment by jspahrsummers** [comment]
Okay, no problem. Thank you for answering all of my silly questions! :sparkles:

I'll merge this very soon (I want to tweak some very small things first). :ship:

**Comment by norio-nomura** [comment]
Yay! Thank you. I hope this will help someone. :smile:

**Pull request merged**
