### PR TITLE
Will add a Property value for the isOn value

### PR DESCRIPTION
**Pull request by cristianames92**
This PR is related to https://github.com/ReactiveCocoa/ReactiveSwift/pull/160 and intends to make a simpler way of composing switches with the `On` values and the `Enable` State.

### CODE REVIEW

**Comment by mdiep** [comment]
Thanks for the PR!

We've come to the conclusion that `Property` isn't an appropriate abstraction for reactive versions of UIKit properties. Since the underlying properties aren't KVO compatible and only send events for user changes (not programatic ones), the `Property.value` has very weird semantics.

Any UIKit properties should be exposed as a `Signal` and/or `BindingTarget`.

**Comment by cristianames92** [comment]
Thanks @mdiep for the quick response, but what about the case when you try to make a composition using different Switches (In this case). You only have the `isOnValues` signal for this purpose but you will not have the very first value, so you will have to make either a producer out of it or a property. The other thing is the `isEnableValues` signal. Why this signal isn't part of the extension yet? In my case i have to make a composition using this state, something that with Rex i could do easily. I'm maybe missing some new structures for this purpose, so please tell me if you can about it.

**Comment by andersio** [comment]
We are discouraging ambiguous layering and anti-patterns.

> You only have the isOnValues signal for this purpose but you will not have the very first value, so you will have to make either a producer out of it or a property.

The view itself should not be the source of truth, but the controller or the view model that bind with it.

> The other thing is the isEnableValues signal. Why this signal isn't part of the extension yet?

Whether a control is enabled or not is unanimously decided by the controller or the view model. User interactions would not affect `isEnabled` in any sense, so there is no point to have it (so as many other properties).

Related issue: #3310

**Comment by cristianames92** [comment]
@andersio you are right about the responsibilities in this case of the UISwitch and the anti patterns. However i still think that even if the programmer is the one who controls the enabled state of the UISwitch, i don't think that it's a bad idea to have the property, for the cases when are combining the state of the switch with the enabled state of it. It's more clear to use this than mixing your inner state with the state of the switch for this purpose.

**Comment by andersio** [comment]
> for the cases when are combining the state of the switch with the enabled state of it. It's more clear to use this than mixing your inner state with the state of the switch for this purpose.

The availability of the button is determined by your business logic, and propagates to your view. The state change of the button is originated from user interactions with your view, and propagates back to your business logic. They are in a reverse direction to to each other, and I do not see why you'd combine them together.



P.S. #3353 is related if you are interested.

**Comment by cristianames92** [comment]
I see what you mean. Then i think that this pr is correctly closed.

**Pull request closed without merging**
