### PR TITLE
Mitigate a regression in type inference.

### PR DESCRIPTION
**Pull request by andersio**
https://bugs.swift.org/browse/SR-7346

### CODE REVIEW

**Comment by mdiep** [comment]
This is fine, but we should maybe wait to hear back after your last comment in the ticket? Or clarify whether we should work around it since it appears to be a legitimate swift bug.

**Comment by andersio** [comment]
It breaks builds with Xcode 9.3 which should probably be patched ASAP.

**Comment by mdiep** [comment]
I'm good to ship then.

**Comment by mdiep** [comment]
I'm good to ship then.

**Pull request merged**
