### PR TITLE
support Cocoapods 1.5.0 static framework

### PR DESCRIPTION
**Pull request by mishagray**
#### Checklist
- [x] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by mdiep** [comment]
Seems fine to me. @ikesyo or @andersio?

**Comment by mdiep** [comment]
Let's go for it. 😄

**Comment by andersio** [comment]
`ObjCRuntimeAliases.h` is meant to be private header. This change makes stuff in this header become part of the public API of ReactiveCocoa built with CocoaPods.

**Comment by mishagray** [comment]
@andersio yeah... the public/private issue is more about using getting cocoa pods to generate a functional modulemap for both static and dynamic frameworks.   If somebody smarter than me can figure out how to fix the Cocoapods.podspec to get cocoa pods to generate the write modulemap for both dynamic static frameworks with the header being 'private' that would be better.   

Alternatively... is for somebody to create a custom modulemap that Cocoapods 'likes' for both static/dynamic frameworks.  Either strategy may work.   Is there a Cocoapods podspec expert out there that can figure this out?

But with a lot of developers (myself included) trying to move from dynamic frameworks to static frameworks ... (smaller code! faster load time!) this feels like an ok workaround for now.   This was the only pod I found out of dozens that didn't port very smoothly.

**Pull request merged**
