### PR TITLE
Update Result to 0.4.5

### PR DESCRIPTION
**Pull request by ikesyo**
See https://github.com/antitypical/Result/issues/90 for the details.

### CODE REVIEW

**Comment by NachoSoto** [comment]
I don't know if we'll be making more releases of RAC 3. I'm not against this change, but I think we should merge #2189 into master already.

**Comment by NachoSoto** [comment]
This is not relevant anymore, right?

**Comment by neilpa** [comment]
I was planning on back-porting the fix for #2384 to RAC 3 since it's pretty bad.

**Comment by mdiep** [comment]
This doesn't seem relevant anymore. At the very least, this would need to target a maintenance branch.

**Pull request closed without merging**
