### PR TITLE
Revert tvOS for now

### PR DESCRIPTION
**Pull request by neilpa**
Unless this can be made to work with Xcode 7, this will need to wait until 7.1 GMs.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Can we simply remove the scheme? If it takes a while to merge this back in it's gonna be more work to just revert this.

**Comment by neilpa** [comment]
Sure

**Comment by neilpa** [comment]
Done

**Comment by NachoSoto** [comment]
Thank you :heart:

**Pull request merged**
