### PR TITLE
Adds the compatibility with libraries such as Aspects, jsPatch or wax…

### PR DESCRIPTION
**Pull request by doggy**
…Patch whom hook functions with forwardInvocation:.

### CODE REVIEW

**Comment by doggy** [comment]
In common case, it is efficiently if we preserve the implementation of forwardInvocation: at calling rac_signalForSelector: and use it when necessary.

But it should be updated if it has been replaced after calling rac_signalForSelector:.
Holding and invoke the old implementation will lead to an unexpected situation. (infinite loops, or crashes)

**Comment by doggy** [comment]
Library such as Aspects, jsPatch or waxPatch will swizzle forwardInvocation: at any time during the app running, probably.

P.S. This is an issue reported at [jsPatch's issue list](https://github.com/bang590/JSPatch/issues/292)
And I decided make this PR to RAC after reviewed all related codes between RAC and jsPatch.

**Comment by andersio** [comment]
We have moved the ObjC framework to [ReactiveObjC](https://github.com/ReactiveCocoa/ReactiveObjC). Would you mind to reopen it there?

**Comment by doggy** [comment]
acknowledge

**Pull request closed without merging**
