### PR TITLE
propertyOf operator

### PR DESCRIPTION
**Pull request by brow**
Reopening #2185 against `master`:

> I observed today that @neilpa and I have both written almost the same function propertyOf<T>(initialValue: T)(signal: Signal<T, NoError>) -> PropertyOf<T> in RAC3 projects. I've actually pasted it into two of my projects.

> This adds propertyOf to RAC, using @neilpa's documentation and function signature from Rex (which I prefer because it's curried for use with |>) and my implementation from Sukhasana (which I don't strongly prefer over @neilpa's).

> @jspahrsummers did once give some reasons for not including a function like this: https://reactivex.slack.com/archives/reactivecocoa/p1424118385000915

> This is currently crashing tests, possibly because of memory corruption introduced by @noescape.

@jspahrsummers said:
> Could this instead be a PropertyOf initializer?

To do:
- [x] Documentation for new functions/methods
- [x] More tests 
- [x] Separate issue and repro for the memory corruption issue

### CODE REVIEW

**Comment by brow** [comment]
I like the initializers better, and not just because they sidestep the memory corruption issue I was triggering with `|>`. (I'll open a separate issue for that.)

@jspahrsummers This does make it possible to avoid using a `MutableProperty` in the implementation, though I haven't tried that yet. Is that what you had in mind?

**Comment by jspahrsummers** [comment]
Looks good! Using `MutableProperty` is fine.

I'll let this sit for a short while, in case other collaborators have opinions (before we add this to the API that can't break), but I'm :+1: as it stands.

**Comment by 335g** [comment]
Looks good :sparkles:

**Comment by neilpa** [comment]
I'm obviously in favor of letting this sneak in pre-3.0 :wink:

**Comment by neilpa** [comment]
This has sat for long enough, I'm gonna go ahead and merge this.

**Comment by almassapargali** [comment]
I think #2006 can be closed too. Great addition, by the way 👍

**Comment by neilpa** [comment]
Good call

**Pull request merged**
