### PR TITLE
modern swift fix

### PR DESCRIPTION
**Pull request by Nirma**
I believe this is a cleaner way to write this.

Hope it helps!

### CODE REVIEW

**Comment by NachoSoto** [comment]
Yup, `newValue` is unnecessary, but I wonder if this was meant for clarity?

**Comment by Nirma** [comment]
@NachoSoto Yeah it is a bit of a puzzle as to why it was written since it isnt needed.
I think deleting it will make the codebase more uniform but thats just my two cents.

What do you think?

**Comment by neilpa** [comment]
I prefer to still specify `newValue` for setters because it's a "magic" name but doesn't look like it (e.g I wish the language had used `$0` for this like with closures).

**Comment by NachoSoto** [comment]
Now that you say it @neilpa, I've been bitten by using the propety name instead of `newValue` so many times, that I think being explicit here is better :+1: 

Thanks for the PR though @Nirma!

**Pull request closed without merging**
