### PR TITLE
Fixes for Swift 3.0 beta 3

### PR DESCRIPTION
**Pull request by NachoSoto**
## Changes:

- Defined `SWIFT_VERSION` to 3.0 to fix compilation in Xcode 8.0 beta 3

Without this, Xcode fails with the following error:
> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

screen shot 2016-07-18 at 12 56 01

- `Observer`: moved `next` to be the first parameter now that order is taken into account. See [SR-0060](https://github.com/apple/swift-evolution/blob/master/proposals/0060-defaulted-parameter-order.md).
- `SignalProducer.on` and `Signal.on`: moved `next` before `failed` now that order is taken into account. See [SR-0060](https://github.com/apple/swift-evolution/blob/master/proposals/0060-defaulted-parameter-order.md).

- Fixed a few warnings regarding syntax changes.

- Fixed warning for redundant type checking by moving the check at compile time.

- Updated `Quick` and `Nimble`.

## TODO:

- [ ] Just wait for [Travis](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-8)... [they're so slow](https://twitter.com/NachoSoto/status/760570441207603201).

### CODE REVIEW

**Comment by NachoSoto** [comment]
I'm adding a few more changes, one minute!

**Comment by NachoSoto** [comment]
Okay this is ready for review now!

**Comment by NachoSoto** [comment]
Tests failing because Travis has not updated to beta 3 yet.

**Comment by mdiep** [comment]
Looks good to me, but I don't want to merge without CI. 😞

**Comment by NachoSoto** [comment]
Sure, I'm fine waiting. Anyone can pick up this branch in the meantime if they need to :)
Hopefully Travis will update quickly.

**Comment by NachoSoto** [comment]
I just rebased this. There's still no beta3 in Travis :(

**Comment by mdiep** [comment]
> I just rebased this. There's still no beta3 in Travis :(

I know, it's killing me. Are there any alternatives to Travis that offer quicker turnarounds?

**Comment by NachoSoto** [comment]
I'm rebasing this and updating it for beta 4

**Comment by NachoSoto** [comment]
I'm going to merge this with just beta 3 support to avoid having 4-levels-deep PRs, and work on beta 4 separately. I hope that's ok.

**Pull request merged**
