### PR TITLE
Update Carthage xcconfigs to 1.1

### PR DESCRIPTION
**Pull request by iby**
This allows building Carthage XCFrameworks with support for Apple Silicone. This is a counterpart for ReactiveCocoa/ReactiveSwift#832 – once that is accepted also need to update ReactiveSwift to latest.

#### Checklist
- [x] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by iby** [comment]
@andersio can we review this and the ReactiveSwift PR and make a patch release to allow proper Apple Silicon XCFramework building via Carthage? 🙏

**Comment by iby** [comment]
@andersio approve CI please.

**Comment by andersio** [comment]
Do the newer xcconfigs have warnings as error enabled by any chance?

**Comment by iby** [comment]
Definitely know that `TREAT_WARNINGS_AS_ERRORS` come enabled for both Swift and GCC lately as default, but don't think that has changed in xcconfigs, not since 2019 – been upgrading all of my projects to disable it lately.

**Comment by iby** [comment]
Yep. There's a few deprecations and tests would fail because of that. Plus a few warnings. Gonna do some tidying up.

**Comment by iby** [comment]
@andersio Yep. ReactiveSwift already has them all disabled. Did the same for ReactiveCocoa, updated dependencies and did the same tidying up as per ReactiveCocoa/ReactiveSwift#833.

**Comment by iby** [comment]
@andersio a polite bump.

**Comment by iby** [comment]
@andersio more polite Friday bumping! 👋

**Pull request merged**
