### PR TITLE
Make UITextField and UITextView text and attributedText signals non-optional.

### PR DESCRIPTION
**Pull request by Marcocanc**
It looks like (at least on iOS 11) it is not possible for `UITextField` and `UITextView` to return `nil` on their `text` and `attributedText` values, even when setting any of them to nil (a simple Playground will prove this). It seems that Apple has [changed this over time](https://stackoverflow.com/questions/18741335/textfield-is-returning-nil-when-it-is-empty/18741469), but I think it would make sense (at least for `text`) to not be optional.

I also noticed that the `UITextView` signals were already force-unwrapping `text` and `attributedText`.

#### Checklist
- [x] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by mdiep** [comment]
This seems fine to me. @andersio?

**Comment by mdiep** [comment]
@Marcocanc I think if you update the CHANGELOG, we can go ahead and merge this.

**Comment by Marcocanc** [comment]
@mdiep Alright, will do. There's one more thing though: `attributedTextValues` and `continuousAttributedTextValues` on UITextField. Do you think it's fine to use `?? NSAttributedText()` there?

**Comment by andersio** [comment]
@mdiep I believe it was modelled as optional originally so that the API matches that of UITextField. I don't see any technical problem for the change though, since Apple sticks with it being IUO for multiple SDK iterations now.

**Comment by mdiep** [comment]
I'm okay to use `??`. 👍

**Comment by mdiep** [comment]
@Marcocanc Do you want to merge master into this? It's not passing CI (and the CHANGELOG needs an update). We'll be releasing a new major version soon, and I'd like to get this in.

**Comment by mdiep** [comment]
This has another conflict. 😓 Sorry!

**Comment by mdiep** [comment]
Thanks for all your work on this!

**Pull request merged**
