### PR TITLE
Re-added tvOS scheme

### PR DESCRIPTION
**Pull request by NachoSoto**
Pending: 
- [x] Update the `Result` reference once https://github.com/antitypical/Result/pull/106 is merged.

### CODE REVIEW

**Comment by ikesyo** [comment]
We must not enable bitcode for Mac target, see https://github.com/antitypical/Result/pull/104.

**Comment by NachoSoto** [comment]
Thanks @ikesyo. Done:
screen shot 2015-10-22 at 19 55 23

**Comment by ikesyo** [comment]
:+1:

**Comment by NachoSoto** [comment]
All right, ready!

**Comment by NachoSoto** [comment]
Thank you!

**Pull request merged**
