### PR TITLE
Preparation for Swift Package Manager

### PR DESCRIPTION
**Pull request by fabio-cerdeiral-ck**
In preparation of adding support for Swift Package Manager, this PR includes some necessary changes:

1. Add conditional checks on most files
2. Separate Swift source files from ObjC source files
3. Rename a couple of files to avoid name collision

This work is mentioned on #3676 
After we merge this PR, adding Swift PM support will be a really small effort

#### Checklist
- [x] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by fabio-cerdeiral-ck** [comment]
@mdiep @andersio @jspahrsummers any thoughts on this? This is the "noisy" part of the work needed in order to support Swift PM. 
If we can get this in, the next PR on SPM should be all about the `Package.swift` configuration.

**Comment by fabio-cerdeiral-ck** [comment]
@mdiep Hey Matt, do you know when you'd have time to look into this?

**Comment by fabio-cerdeiral-ck** [comment]
@jspahrsummers @mdiep @joshaber @ikesyo @kastiglione 
Anyone?? Really guys .. this would be extremely helpful to keep moving `ReactCocoa` forward. We need better support here!!
This is a non-breaking change, 100% backward compatible, and it'd open the way for Swift Package Manager PR, which should be super small after this change.
I'm open to feedback and willing to help, but I need better support in order to do. Thank you!

**Comment by fabio-cerdeiral-ck** [comment]
@mdiep @andersio @jspahrsummers @ikesyo ^^ 🙏

**Comment by kastiglione** [comment]
@fabio-cerdeiral-ck I haven't been involved in a while, so unfortunately I'm not in a position to review.

**Comment by andersio** [comment]
Sorry for the slow response. 🤦‍♂

**Pull request merged**
