### PR TITLE
Change void return types to using Void

### PR DESCRIPTION
**Pull request by ikesyo**
See http://ericasadun.com/2015/05/11/swift-vs-void/.

### CODE REVIEW

**Comment by neilpa** [comment]
Personally I prefer `() -> ()`, but it's probably better to be consistent with apple here.

**Comment by neilpa** [comment]
I want to wait for github/swift-style-guide#39 to shake out before merging.

**Comment by ikesyo** [comment]
Oh, thank you for the opening it! :bow: I'll wait.

**Comment by jspahrsummers** [comment]
Per https://github.com/github/swift-style-guide/issues/39#issuecomment-109443211, I think we'd like to continue using `()`.

Thanks, though!

/cc @robrix

**Comment by ikesyo** [comment]
Yep, thank you all for the discussion! :wink:

**Pull request closed without merging**
