### PR TITLE
Fix 2515 (deadlock in SignalProducer.buffer)

### PR DESCRIPTION
**Pull request by Vadim-Yelagin**
https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2515

### CODE REVIEW

**Comment by NachoSoto** [comment]
It's hard to tell what this is trying to fix without a new failing unit test. Do you think you could come up with one so that:
- We can verify that there is in fact a dead-locking scenario.
- We can verify that this change fixes it, and it doesn't break any existing test.
- We can be sure that the problem is never introduced again in the future.

**Comment by neilpa** [comment]
I haven't looked at the code yet but I'm assuming this uses queue-drain to resolve. It's something which has been discussed in the past but has been decided against because it has it's own pitfalls.

**Comment by neilpa** [comment]
cc @jspahrsummers since I wasn't really involved back then.

**Comment by vadim-fueled** [comment]
I haven't tried adding any new tests, but all tests pass even if I simply remove the lock in question. If there's been a lot of consideration of different pitfalls of different approaches, that would be really helpful to have tests that illustrate those pitfalls. I've posted a snippet deadlocking on nested observing on a single queue in https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2515
I think I can see how the lock can help when adding an observer on one thread and inserting an event on another thread. But either was this half-hearted implementation of recursive locking (which by itself is an anti-pattern and can't comprehensibly protect from deadlocks when calling arbitrary callback code while locked) doesn't seem like the way to go.
I'm sorry I don't have more time to write tests or otherwise work on this matter at this moment.

**Comment by vadim-fueled** [comment]
What if instead of having a single lock per buffer we make a lock for every observer and store it in the state in pair with the observer? This way when a new observer is added, only its newly created lock gets locked, which will deadlock if the observer tries to insert a new event, but not if it adds a new observer. When inserting a new event, the locks get locked one-by-one when iterating over observers. This will too deadlock when trying to insert an event, but not when adding a new observer. It's the same desired behavior but without the need for recursive locks.

**Comment by Vadim-Yelagin** [comment]
Oops, that was me.
I'm going to close this PR and move the conversation back to https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2515

**Pull request closed without merging**
