### PR TITLE
Nullability Annotation for `RACCommand` and `RACSignal`.

### PR DESCRIPTION
**Pull request by andersio**
Per @ikesyo's suggestions, these are cherry-picked from the `swift3.0` branch. They were meant to wipe all surprising optionals away from `ObjectiveCBridging.swift`.

_(Feel free to take over and progress on it. :-].)_

### CODE REVIEW

**Comment by andersio** [comment]
Got green checks locally, but Travis is somehow stuck. :-[

**Comment by mdiep** [comment]
Which version of Xcode are you using locally? Is it the same version as Travis?

**Comment by andersio** [comment]
It should be 7.3.1.

**Comment by andersio** [comment]
Just ran again locally...
```
Test Suite 'ReactiveCocoaTests.xctest' passed at 2016-07-11 00:22:16.757.
	 Executed 1456 tests, with 0 failures (0 unexpected) in 34.352 (36.646) seconds
Test Suite 'Quick.framework' started at 2016-07-11 00:22:16.761
Test Suite 'Quick.framework' passed at 2016-07-11 00:22:16.762.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
Test Suite 'All tests' passed at 2016-07-11 00:22:16.763.
	 Executed 1456 tests, with 0 failures (0 unexpected) in 34.352 (36.655) seconds
** TEST SUCCEEDED **

ikbenanders:RAC4 anders$ xcodebuild -version
Xcode 7.3.1
Build version 7D1014
```
But the error forwarding test case in ObjectiveCBridgingSpec failed per the CI log. Hmm...

**Comment by mdiep** [comment]
If it's a hassle (and it's looking to be), I think we can just forget this for RAC 4.

**Comment by andersio** [comment]
I will just close it then. If anyone interested feels free to revive it.

The branch in my fork:
https://github.com/ReactiveCocoa/ReactiveCocoa/tree/nullability-annotation

**Pull request closed without merging**
