### PR TITLE
Fix dropping signal bug on multithreading in SignalProducer.buffer()

### PR DESCRIPTION
**Pull request by norio-nomura**
This fix the Carthage hanging I reported on following:
https://github.com/Carthage/Carthage/pull/474#issuecomment-107307773

See also the description of https://github.com/ReactiveCocoa/ReactiveCocoa/commit/5b41bb51320640fc7be95b81ad89283d831e6582

### CODE REVIEW

**Comment by norio-nomura** [comment]
```swift
			if let token = token {
				disposable.addDisposable {
					observers.modify { (var observers) in
						observers?.removeValueForToken(token)
						return observers
					}
				}
			}
```
`addDisposable()`'s action should use `lock` instead of `Atomic<T>.modify()`.
And `observers` can be changed to non `Atomic`.
The codes inside `if let liveObservers = oldObservers {…}` looks strange to me. But I can't determine how it should be…

**Comment by norio-nomura** [comment]
I should write more description of this.

## About dropping signal bug on multithreading in `SignalProducer.buffer()`
`SignalProducer.buffer()` create a pair of `SignalProducer` and `bufferingObserver`.
These share two lock objects
```
		let lock = NSLock()
		let observers: Atomic<Bag<Signal<T, E>.Observer>?> = Atomic(Bag())
```

The issue caused by two threads
- Thread A call `SignalProducer` adding new observer
- Thread B call `bufferingObserver` putting signal to observers

with following scenario:

1. [B] `bufferingObserver` retrieve `observers` from `Atomic<T>`
2. [A] `SignalProducer` acquires `lock`
3. [B] `bufferingObserver` wait `lock`
4. [A] `SignalProducer` add **new observer** to `observers` inside `Atomic<T>`
5. [A] `SignalProducer` relinquishes `lock`
6. [B] `bufferingObserver` acquires lock and put signal to `observers`.

The **new observer** added on 4. will never receive signal when this happen.

For verifying this scenario, I pushed commit as 5b41bb5
For fixing this scenario, I pushed commit as 109da1e
For reverting 5b41bb5, I pushed commit as 3f11cfe

I verified this fix Carthage hanging I reported on following:
https://github.com/Carthage/Carthage/issues/455#issuecomment-106991205
https://github.com/Carthage/Carthage/pull/474#issuecomment-107307773

**Comment by robrix** [comment]
:ok_hand:

**Comment by norio-nomura** [comment]
:bow:

**Comment by jspahrsummers** [comment]
Thanks, @norio-nomura!

**Pull request merged**
